version: "3.8"
services:
  # authentication:
  #   build:
  #     context: ./authentication
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env

  # user-manager:
  #   build:
  #     context: ./user-manager
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   env_file:
  #     - .env

  anonymiser:
    build:
      context: ./anonymiser
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
