version: "3.8"
services:
  anonymiser:
    build:
      context: ./anonymiser
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
