version: "3.8"
services:
  authentication:
    container_name: authentication
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - chatstodo

  user-manager:
    container_name: user-manager
    build:
      context: ./user-manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - chatstodo

  anonymiser:
    container_name: anonymiser
    build:
      context: ./anonymiser
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - chatstodo

networks:
  chatstodo:
    name: chatstodo
    driver: bridge
