# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatstodo_ml_service_pb2 as chatstodo__ml__service__pb2


class ChatAnalysisServiceStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeChat = channel.unary_unary(
                '/chatstodo_ml_service.ChatAnalysisService/AnalyzeChat',
                request_serializer=chatstodo__ml__service__pb2.UserChatRequest.SerializeToString,
                response_deserializer=chatstodo__ml__service__pb2.ChatAnalysisResponse.FromString,
                )


class ChatAnalysisServiceServicer(object):
    """Define the service
    """

    def AnalyzeChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeChat': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeChat,
                    request_deserializer=chatstodo__ml__service__pb2.UserChatRequest.FromString,
                    response_serializer=chatstodo__ml__service__pb2.ChatAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatstodo_ml_service.ChatAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatAnalysisService(object):
    """Define the service
    """

    @staticmethod
    def AnalyzeChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatstodo_ml_service.ChatAnalysisService/AnalyzeChat',
            chatstodo__ml__service__pb2.UserChatRequest.SerializeToString,
            chatstodo__ml__service__pb2.ChatAnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
