# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatstodo_ml_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63hatstodo_ml_service.proto\x12\x14\x63hatstodo_ml_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n\x04\x43hat\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63hat_message\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x83\x01\n\x0fUserChatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0cmessage_text\x18\x03 \x03(\x0b\x32\x1a.chatstodo_ml_service.Chat\"J\n\x0b\x45ventDetail\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"\xa8\x01\n\x14\x43hatAnalysisResponse\x12\x0e\n\x06userID\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07summary\x18\x03 \x03(\t\x12\r\n\x05tasks\x18\x04 \x03(\t\x12\x31\n\x06\x65vents\x18\x05 \x03(\x0b\x32!.chatstodo_ml_service.EventDetail2y\n\x13\x43hatAnalysisService\x12\x62\n\x0b\x41nalyzeChat\x12%.chatstodo_ml_service.UserChatRequest\x1a*.chatstodo_ml_service.ChatAnalysisResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatstodo_ml_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHAT']._serialized_start=85
  _globals['_CHAT']._serialized_end=177
  _globals['_USERCHATREQUEST']._serialized_start=180
  _globals['_USERCHATREQUEST']._serialized_end=311
  _globals['_EVENTDETAIL']._serialized_start=313
  _globals['_EVENTDETAIL']._serialized_end=387
  _globals['_CHATANALYSISRESPONSE']._serialized_start=390
  _globals['_CHATANALYSISRESPONSE']._serialized_end=558
  _globals['_CHATANALYSISSERVICE']._serialized_start=560
  _globals['_CHATANALYSISSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
