name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            anonymiser,
            authentication,
            telegram,
            ml-functions,
            discord,
            user-manager,
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast2-docker.pkg.dev

      - name: Login to Google Artifact Registry
        run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://asia-northeast2-docker.pkg.dev

      - name: Build and push service image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: asia-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ matrix.service }}/${{ matrix.service }}:${{ github.sha }}
